### ISSUE TITLE
How to limit some ports' speed?

### ISSUE THREAD

**Issue by 1558204459** [magnific0/wondershaper#10]

**Comment by 1558204459** [comment]
Will wondersharper add the such function?

**Comment by magnific0** [comment]
@1558204459 This functionality is not present in wondershaper and will likely not be added unless there is great demand. It is however possible to accomplish this with this script.
Currently filters are added on an ip basis to enforce the rules. But you can easily change this to port based using ```match ip dport 22``` and ```match ip sport 22``` instead of ```ip dst/src 0.0.0.0/0```, here:

- https://github.com/magnific0/wondershaper/blob/master/wondershaper#L207

- https://github.com/magnific0/wondershaper/blob/master/wondershaper#L234

**Comment by freshgeek** [comment]
> Wondershaper会添加这样的功能吗？

I have the same problem
