### ISSUE TITLE
Doesn't work with SYN flood

### ISSUE THREAD

**Issue by fredericoschardong** [magnific0/wondershaper#12]
If you flood a machine with, let's say, this: sudo hping3 -S -p 8000 --flood --rand-source 10.0.0.1

Then wondershape is not able of limiting the incoming traffic.

**Comment by magnific0** [comment]
@fredericoschardong that is quite interesting. Note that as of 1.4 the ingress system has been updated to not drop packets anymore, but to offload it to the virtual ifb interface. Do you reckon this problem is still present in the new setup? For now I'm closing the issue, but please feel free to re-open.
