### ISSUE TITLE
Missing accounting for ADSL linklayer

### ISSUE THREAD

**Issue by netoptimizer** [magnific0/wondershaper#5]
Hi the wondershaper is not taking the linklayer e.g. ADSL/ATM into account, or accounting for any encapsulation overhead.

Just add "linklayer adsl" and "overhead 10" to the TC command

**Comment by magnific0** [comment]
My apologies for replying only so late. 

If you still think these should be added can you elaborate a bit? Is adding ```linklayer adsl``` and ```overhead 10``` suggested for all possible interfaces / cases?

Since this issue is so old and there's a new version out, I'm closing the issue, but please feel free to re-open in case you or someone else wants to expand on this.
